"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from unittest import mock

from rockset.models import *
from test.conftest import EarlyExit, validate_call


def test_get_deployment_settings(get_client, mock_request, request_validator):
    with mock_request:
        rs = get_client
        try:
            rs.DeploymentSettings.get_deployment_settings()
        except EarlyExit as e:
            validate_call(e, request_validator)


def test_update_deployment_settings(get_client, mock_request, request_validator):
    with mock_request:
        rs = get_client
        try:
            rs.DeploymentSettings.update_deployment_settings(
                default_query_vi="rrn:vi:use1a1:123e4567-e89b-12d3-a456-556642440000",
            )
        except EarlyExit as e:
            validate_call(e, request_validator)
