"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import rockset
from rockset.api.queries_api import QueriesApi  # noqa: E501


class TestQueriesApi(unittest.TestCase):
    """QueriesApi unit test stubs"""

    def setUp(self):
        self.api = QueriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_query(self):
        """Test case for cancel_query

        Cancel Query  # noqa: E501
        """
        pass

    def test_get_query(self):
        """Test case for get_query

        Retrieve Query  # noqa: E501
        """
        pass

    def test_get_query_results(self):
        """Test case for get_query_results

        Retrieve Query Results Page  # noqa: E501
        """
        pass

    def test_list_active_queries(self):
        """Test case for list_active_queries

        List Queries  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Execute SQL Query  # noqa: E501
        """
        pass

    def test_validate(self):
        """Test case for validate

        Validate Query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
