"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import rockset
from rockset.api.aliases_api import Aliases  # noqa: E501


class TestAliases(unittest.TestCase):
    """Aliases unit test stubs"""

    def setUp(self):
        self.api = Aliases()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_alias(self):
        """Test case for create_alias

        Create Alias  # noqa: E501
        """
        pass

    def test_delete_alias(self):
        """Test case for delete_alias

        Delete Alias  # noqa: E501
        """
        pass

    def test_get_alias(self):
        """Test case for get_alias

        Retrieve Alias  # noqa: E501
        """
        pass

    def test_list_aliases(self):
        """Test case for list_aliases

        List Aliases  # noqa: E501
        """
        pass

    def test_update_alias(self):
        """Test case for update_alias

        Update Alias  # noqa: E501
        """
        pass

    def test_workspace_aliases(self):
        """Test case for workspace_aliases

        List Aliases in Workspace  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
