"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import rockset
from rockset.model.format_params import FormatParams
from rockset.model.source import Source
from rockset.model.source_azure_service_bus import SourceAzureServiceBus
from rockset.model.status_azure_service_bus import StatusAzureServiceBus
globals()['FormatParams'] = FormatParams
globals()['Source'] = Source
globals()['SourceAzureServiceBus'] = SourceAzureServiceBus
globals()['StatusAzureServiceBus'] = StatusAzureServiceBus
from rockset.model.azure_service_bus_source_wrapper import AzureServiceBusSourceWrapper


class TestAzureServiceBusSourceWrapper(unittest.TestCase):
    """AzureServiceBusSourceWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureServiceBusSourceWrapper(self):
        """Test AzureServiceBusSourceWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AzureServiceBusSourceWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
