"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import rockset
from rockset.api.views_api import ViewsApi  # noqa: E501


class TestViewsApi(unittest.TestCase):
    """ViewsApi unit test stubs"""

    def setUp(self):
        self.api = ViewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_view(self):
        """Test case for create_view

        Create View  # noqa: E501
        """
        pass

    def test_delete_view(self):
        """Test case for delete_view

        Delete View  # noqa: E501
        """
        pass

    def test_get_view(self):
        """Test case for get_view

        Retrieve View  # noqa: E501
        """
        pass

    def test_list_views(self):
        """Test case for list_views

        List Views  # noqa: E501
        """
        pass

    def test_update_view(self):
        """Test case for update_view

        Update View  # noqa: E501
        """
        pass

    def test_workspace_views(self):
        """Test case for workspace_views

        List Views in Workspace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
