"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import rockset
from rockset.api.query_lambdas_api import QueryLambdasApi  # noqa: E501


class TestQueryLambdasApi(unittest.TestCase):
    """QueryLambdasApi unit test stubs"""

    def setUp(self):
        self.api = QueryLambdasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_query_lambda(self):
        """Test case for create_query_lambda

        Create Query Lambda  # noqa: E501
        """
        pass

    def test_create_query_lambda_tag(self):
        """Test case for create_query_lambda_tag

        Create Query Lambda Tag  # noqa: E501
        """
        pass

    def test_delete_query_lambda(self):
        """Test case for delete_query_lambda

        Delete Query Lambda  # noqa: E501
        """
        pass

    def test_delete_query_lambda_tag(self):
        """Test case for delete_query_lambda_tag

        Delete Query Lambda Tag Version  # noqa: E501
        """
        pass

    def test_delete_query_lambda_version(self):
        """Test case for delete_query_lambda_version

        Delete Query Lambda Version  # noqa: E501
        """
        pass

    def test_execute_query_lambda(self):
        """Test case for execute_query_lambda

        Execute Query Lambda By Version  # noqa: E501
        """
        pass

    def test_execute_query_lambda_by_tag(self):
        """Test case for execute_query_lambda_by_tag

        Execute Query Lambda By Tag  # noqa: E501
        """
        pass

    def test_get_query_lambda_tag_version(self):
        """Test case for get_query_lambda_tag_version

        Retrieve Query Lambda Tag  # noqa: E501
        """
        pass

    def test_get_query_lambda_version(self):
        """Test case for get_query_lambda_version

        Retrieve Query Lambda Version  # noqa: E501
        """
        pass

    def test_list_all_query_lambdas(self):
        """Test case for list_all_query_lambdas

        List Query Lambdas  # noqa: E501
        """
        pass

    def test_list_query_lambda_tags(self):
        """Test case for list_query_lambda_tags

        List Query Lambda Tags  # noqa: E501
        """
        pass

    def test_list_query_lambda_versions(self):
        """Test case for list_query_lambda_versions

        List Query Lambda Versions  # noqa: E501
        """
        pass

    def test_list_query_lambdas_in_workspace(self):
        """Test case for list_query_lambdas_in_workspace

        List Query Lambdas in Workspace  # noqa: E501
        """
        pass

    def test_update_query_lambda(self):
        """Test case for update_query_lambda

        Update Query Lambda  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
