# coding: utf-8

"""
    REST API

    Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CreateQueryLambdaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'sql': 'QueryLambdaSql'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'sql': 'sql'
    }

    def __init__(self, name=None, description=None, sql=None, _configuration=None):  # noqa: E501
        """CreateQueryLambdaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._description = None
        self._sql = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        self.sql = sql

    @property
    def name(self):
        """Gets the name of this CreateQueryLambdaRequest.  # noqa: E501

        Query Lambda name  # noqa: E501

        :return: The name of this CreateQueryLambdaRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateQueryLambdaRequest.

        Query Lambda name  # noqa: E501

        :param name: The name of this CreateQueryLambdaRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CreateQueryLambdaRequest.  # noqa: E501

        optional description  # noqa: E501

        :return: The description of this CreateQueryLambdaRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateQueryLambdaRequest.

        optional description  # noqa: E501

        :param description: The description of this CreateQueryLambdaRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def sql(self):
        """Gets the sql of this CreateQueryLambdaRequest.  # noqa: E501

        Query Lambda SQL query  # noqa: E501

        :return: The sql of this CreateQueryLambdaRequest.  # noqa: E501
        :rtype: QueryLambdaSql
        """
        return self._sql

    @sql.setter
    def sql(self, sql):
        """Sets the sql of this CreateQueryLambdaRequest.

        Query Lambda SQL query  # noqa: E501

        :param sql: The sql of this CreateQueryLambdaRequest.  # noqa: E501
        :type: QueryLambdaSql
        """
        if self._configuration.client_side_validation and sql is None:
            raise ValueError("Invalid value for `sql`, must not be `None`")  # noqa: E501

        self._sql = sql

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateQueryLambdaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateQueryLambdaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateQueryLambdaRequest):
            return True

        return self.to_dict() != other.to_dict()
